/*
 * Mock Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;
using SWKOM_paperless.BusinessLogic.Interfaces;
using Document = SWKOM_paperless.BusinessLogic.Entities.Document;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class SearchApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="term"></param>
        /// <param name="limit"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/api/search/autocomplete")]
        [ValidateModelState]
        [SwaggerOperation("AutoComplete")]
        public virtual async Task<ListResponse<Document>> AutoComplete(
            [FromQuery (Name = "term")]string term, 
            [FromQuery (Name = "limit")]int? limit,
            [FromServices] IElasticSearchLogic elasticSearchLogic
            )
        {
            var result = await elasticSearchLogic.SearchDocumentsAsync(term, "documents");
            return new ListResponse<Document>()
            {
                Count = result.Count,
                Results = result
            };
        }
    }
}
